graph TD
  subgraph Input ["Input (No Caller)"]
    ApiService_js_validateApiToken_:::neural
    ApiService_js_doPost:::neural
    ApiService_js_apiLogin_:::neural
    ApiService_js_dispatchApiAction_:::neural
    ApiService_js_apiSubmitScanIdempotent_:::neural
    AuthService_js_readKaryawanRowsFromCache_:::neural
    AuthService_js_getLoginAttemptCount_:::neural
    AuthService_js_writeKaryawanRowsToCache_:::neural
    AuthService_js_registerLoginFailure_:::neural
    AuthService_js_roleFromJabatan_:::neural
    AuthService_js_findKaryawanByNik_:::neural
    AuthService_js_getKaryawanRows_:::neural
    AuthService_js_clearLoginAttempts_:::neural
    BarcodeService_js_padSeq_:::neural
    BarcodeService_js_getCellValue_:::neural
    BarcodeService_js_handleKirimMesin_:::neural
    BarcodeService_js_handleTerimaWrm_:::neural
    BarcodeService_js_classifyBarcode_:::neural
    BarcodeService_js_allocateChildBarcodes_:::neural
    BarcodeService_js_escapeRegex_:::neural
    BarcodeService_js_formatTimestamp_:::neural
    BarcodeService_js_handleChildCheckpoint_:::neural
    BarcodeService_js_getNextChildSequence_:::neural
    BarcodeService_js_lookupMesinFromLog_:::neural
    BarcodeService_js_getShift_:::neural
    Code_js_include:::neural
    MaterialService_js_deleteMaterialMaster_:::neural
    MaterialService_js_isMidUsedAnywhere_:::neural
    MaterialService_js_resolveDeskCol_:::neural
    SheetService_js_getSpreadsheet_:::neural
    SheetService_js_parseMonth_:::neural
    SheetService_js_queryReprintSheet_:::neural
    SheetService_js_appendReprintRow_:::neural
    SheetService_js_parseSapDate_:::neural
    SheetService_js_findRowByColumnValue_:::neural
    StockService_js_getNormalizedShiftNum_:::neural
    StockService_js_readAllBarcodeRows_:::neural
    StockService_js_getRealLastRowAndTrim_:::neural
    StockService_js_executeShiftRollover_:::neural
    StockService_js_toDateOrNull_:::neural
    StockService_js_getMinMaxMap_:::neural
    StockService_js_parseMb51Timestamp_:::neural
    StockService_js_getNormalizedDateStr_:::neural
    StockService_js_formatDateLabel_:::neural
  end
  subgraph Output ["Output (No Callees)"]
    AuthService_js_requireRole_:::neural
    AuthService_js_resolveRole_:::neural
    AuthService_js_login_:::neural
    BarcodeService_js_getReprintData_:::neural
    BarcodeService_js_getShiftBounds_:::neural
    BarcodeService_js_processScan_:::neural
    BarcodeService_js_saveBatchReprint_:::neural
    BarcodeService_js_deleteReprintBarcode_:::neural
    Code_js_getTspMesinMonitoring:::neural
    Code_js_getHistoricalMesinStock:::neural
    Code_js_deleteMinMaxSettingApi:::neural
    Code_js_login:::neural
    Code_js_konfirmasiItemStokShift:::neural
    Code_js_getReservasiOptions:::neural
    Code_js_saveMinMaxSettingApi:::neural
    Code_js_getMinMaxSettingsApi:::neural
    Code_js_konfirmasiNeracaStokShift:::neural
    Code_js_getOperatorConsumption:::neural
    Code_js_getHistoricalTspStock:::neural
    Code_js_saveBatchReprint:::neural
    Code_js_doGet:::neural
    Code_js_getMesinList:::neural
    Code_js_saveMinMaxBatchApi:::neural
    Code_js_deleteReprintBarcode:::neural
    Code_js_saveMaterialBatchApi:::neural
    Code_js_submitScan:::neural
    Code_js_saveMaterialApi:::neural
    Code_js_tarikStokAwalShift:::neural
    Code_js_getShiftDispatches:::neural
    Code_js_getPortalHistory:::neural
    Code_js_getValidatorData:::neural
    Code_js_getOperatorReceipts:::neural
    Code_js_getMesinStock:::neural
    Code_js_getTspStock:::neural
    Code_js_getShiftReceipts:::neural
    Code_js_deleteMaterialApi:::neural
    Code_js_getReprintData:::neural
    Code_js_getMaterialListApi:::neural
    MaterialService_js_getMaterialMap_:::neural
    MaterialService_js_saveMaterialBatch_:::neural
    MaterialService_js_deleteMaterial_:::neural
    MaterialService_js_getSupplierMap_:::neural
    MaterialService_js_migrateMaterialMasterIfEmpty_:::neural
    MaterialService_js_saveMaterialMaster_:::neural
    MaterialService_js_getMaterialList_:::neural
    SheetService_js_getSheet_:::neural
    SheetService_js_getHeaderMap_:::neural
    SheetService_js_getReservasiList_:::neural
    SheetService_js_appendLog_:::neural
    SheetService_js_validateMidInReservasi_:::neural
    SheetService_js_findBarcodeRow_:::neural
    SheetService_js_lookupWrmIncoming_:::neural
    SheetService_js_appendBarcodeRow_:::neural
    SheetService_js_updateBarcodeCell_:::neural
    SheetService_js_ensureSheetsReady_:::neural
    StockService_js_computeTspStock_:::neural
    StockService_js_konfirmasiStokShift_:::neural
    StockService_js_normalizeMid_:::neural
    StockService_js_incrementStockCell_:::neural
    StockService_js_saveMinMaxSetting:::neural
    StockService_js_computePortalHistory_:::neural
    StockService_js_deleteMinMaxSetting_:::neural
    StockService_js_computeOperatorConsumption_:::neural
    StockService_js_computeHistoricalTspStock_:::neural
    StockService_js_computeHistoricalMesinStock_:::neural
    StockService_js_ensureMidInActiveShift_:::neural
    StockService_js_computeMesinStock_:::neural
    StockService_js_tarikStokAwalShift_:::neural
    StockService_js_computeOperatorReceipts_:::neural
    StockService_js_saveMinMaxBatch_:::neural
    StockService_js_getMinMaxSettings:::neural
    StockService_js_getMinMaxSheet_:::neural
    StockService_js_konfirmasiItemStokShift_:::neural
    StockService_js_computeValidator_:::neural
    StockService_js_computeTspMesinMonitoring_:::neural
    StockService_js_computeShiftDispatches_:::neural
    StockService_js_computeShiftReceipts_:::neural
  end